steps:
  - name: 'python:3.12'  # Full image has curl pre-installed
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # 1. Install uv
        curl -LsSf https://astral.sh/uv/install.sh | sh
        
        # 2. Run build using the actual install path found in your logs
        /builder/home/.local/bin/uv build

# Store the resulting .whl and .tar.gz files
artifacts:
  objects:
    location: 'gs://vertex-482922_cloudbuild/dist/'
    paths: ['dist/*']
options:
  logging: CLOUD_LOGGING_ONLY
