steps:
  - name: 'python:3.12-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Use $$ to tell Cloud Build these are shell variables, not build substitutions
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$$HOME/.cargo/bin:$$PATH"
        
        /root/.cargo/bin/uv build

# Store the resulting .whl and .tar.gz files
artifacts:
  objects:
    location: 'gs://vertex-482922_cloudbuild/dist/'
    paths: ['dist/*']
options:
  logging: CLOUD_LOGGING_ONLY
