steps:
  - name: 'python:3.12-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # 1. Install curl (required for the installer)
        apt-get update && apt-get install -y curl ca-certificates
        
        # 2. Install uv
        curl -LsSf https://astral.sh/uv/install.sh | sh
        
        # 3. Build using the absolute path to the uv binary
        /root/.cargo/bin/uv build

# Store the resulting .whl and .tar.gz files
artifacts:
  objects:
    location: 'gs://vertex-482922_cloudbuild/dist/'
    paths: ['dist/*']
options:
  logging: CLOUD_LOGGING_ONLY
